import type { Metadata } from "next";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import ThemeProviderWrapper from "./provider/ThemeProvider";

import NavBar from "@/components/navBar/NavBar";
import Footer from "@/components/footer/Footer";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProviderWrapper >
      <html lang="en">
        <body>
          <AppRouterCacheProvider>
            <NavBar />
            <main className="main-container">{children}</main>
            <Footer />
          </AppRouterCacheProvider>
        </body>
      </html>
     </ThemeProviderWrapper>
  );
}
